### ISSUE TITLE
feedback插件 频道内无法正常回复

### ISSUE THREAD

**Issue by Ember2024** [koishijs/common#9]
![{AA78BB35-E40B-49f9-A60F-E54B5E4B4EA6}](https://github.com/koishijs/common/assets/131529788/e7c3ad20-5339-4c8f-9752-f819597b90bc)
![{B5D81B05-EA22-4c5d-8A90-C4C4AD4F2228}](https://github.com/koishijs/common/assets/131529788/3f29b65c-f9a4-4205-817e-29d03c13ecdb)

**Comment by shigma** [comment]
feedback 插件依赖主动消息。正常情况下，QQ 的主动消息受到严格的限制。请检查自己的机器人有没有发送主动消息的权限。

**Comment by Ember2024** [comment]
![f5666148b2d3866272b39039c3544768_720](https://github.com/koishijs/common/assets/131529788/81eecfe0-878a-4026-a226-9ed740c506eb)

**Comment by shigma** [comment]
接受机器人推送是频道的设置，而非机器人的权限，机器人只有「频道接受推送+本身有权限」的情况下才能发送主动消息。

**Comment by Ember2024** [comment]
私域bot默认不是拥有主动推送吗
如果没有主动推送，那这条消息怎么发的
![image](https://github.com/koishijs/common/assets/131529788/45241f22-68a7-41bf-a920-16bc8c95036a)

**Comment by Ember2024** [comment]
![image](https://github.com/koishijs/common/assets/131529788/fe14d6bd-2f9b-4454-8dd7-462924fc9567)
主动消息在频道主或管理设置了情况下，按设置的数量进行限频

**Comment by Ember2024** [comment]
我可以正常订阅MESSAGE_AUDIT

**Comment by Ember2024** [comment]
日志没有任何报错

**Comment by Ember2024** [comment]
如果我将沙盒设置成反馈频道进行反馈回复后可以正常推送

**Comment by Ember2024** [comment]
并且我没艾特机器人，哪里来的消息id给我被动回复用呢？

**Comment by shigma** [comment]
你 at 机器人，机器人【在 5 分钟内】，【在同一个频道内】，【at 你并回复】，这个叫被动消息。

你 at 机器人，机器人跑到另一个反馈频道发送消息，这个叫主动消息。

**Comment by Ember2024** [comment]
![image](https://github.com/koishijs/common/assets/131529788/933de0e3-c18e-42c4-8b1b-12c014a94ec6)

**Comment by shigma** [comment]
唉我加个错误提示吧。你这个情况甚至没到主动消息这一步就挂了，没找到机器人。

请问你是如何配置的？

1. 通过 `feedback -r`
2. 编辑配置文件

**Comment by Ember2024** [comment]
feedback -r

**Comment by shigma** [comment]
更新了 2.1.1 版本。升级后会有更明确的错误提示。之后请继续回复此 issue。

**Comment by Ember2024** [comment]
> 你 at 机器人，机器人【在 5 分钟内】，【在同一个频道内】，【at 你并回复】，这个叫被动消息。
> 
> 你 at 机器人，机器人跑到另一个反馈频道发送消息，这个叫主动消息。

呃，我重装了一遍，报错没了

**Comment by Ember2024** [comment]
我想问一下，如果我不艾特机器人，直接发命令，机器人没有艾特回复我，直接把消息发到频道里，这个算什么

**Comment by shigma** [comment]
能用就好，如果以后还发现问题可以重新说。

**Comment by shigma** [comment]
> 我想问一下，如果我不艾特机器人，直接发命令，机器人没有艾特回复我，直接把消息发到频道里，这个算什么

这个是私域，私域没有主动被动之分，也不会受到限制。但是私域有人数限制，频道人数超过一定量就得强制公域了。

Koishi 有论坛贴和群用于讨论 QQ 频道 / QQ 群的接入。里面有很多熟悉这些琐碎流程和注意事项的开发者。如果还有什么问题，也欢迎前来讨论。
